const fs = require('fs');

const dict = {
"Accept": { m: "গ্রহণ করা", e: "I accept your proposal." },
"Accident": { m: "দুর্ঘটনা", e: "He had a car accident." },
"Account": { m: "হিসাব", e: "I have a bank account." },
"Achieve": { m: "অর্জন করা", e: "He works hard to achieve his goals." },
"Active": { m: "সক্রিয় / কর্মঠ", e: "She is an active student." },
"Activity": { m: "কার্যকলাপ", e: "Reading is a good activity." },
"Actually": { m: "আসলে", e: "I actually don't know the answer." },
"Add": { m: "যোগ করা", e: "Add some sugar to the tea." },
"Addition": { m: "যোগ / সংযোজন", e: "In addition to English, he speaks French." },
"Address": { m: "ঠিকানা", e: "What is your home address?" },
"Adult": { m: "প্রাপ্তবয়স্ক", e: "This movie is for adults only." },
"Advantage": { m: "সুবিধা", e: "There are many advantages of reading books." },
"Adventure": { m: "দুঃসাহসিক কাজ", e: "They went on an adventure in the jungle." },
"Advice": { m: "উপদেশ", e: "I need your advice." },
"Advise": { m: "উপদেশ দেওয়া", e: "The doctor advised him to rest." },
"Affect": { m: "প্রভাবিত করা", e: "The weather can affect our mood." },
"Afraid": { m: "ভীত", e: "She is afraid of snakes." },
"Afternoon": { m: "বিকাল", e: "Let's play football this afternoon." },
"Agent": { m: "প্রতিনিধি", e: "He is a travel agent." },
"Agreement": { m: "চুক্তি / সম্মতি", e: "They signed a peace agreement." },
"Agriculture": { m: "কৃষি", e: "Agriculture is our main source of income." },
"Ahead": { m: "সামনে / অগ্রগামী", e: "Go straight ahead." },
"Airport": { m: "বিমানবন্দর", e: "We arrived at the airport early." },
"Album": { m: "অ্যালবাম", e: "I have a photo album." },
"Alive": { m: "জীবিত", e: "The insect is still alive." },
"Alphabet": { m: "বর্ণমালা", e: "There are 26 letters in the English alphabet." },
"Already": { m: "ইতোমধ্যে", e: "I have already finished my homework." },
"Alternative": { m: "বিকল্প", e: "We have no alternative plan." },
"Although": { m: "যদিও", e: "Although it was raining, we went out." },
"Always": { m: "সর্বদা", e: "I always brush my teeth." },
"Amazing": { m: "চমকপ্রদ", e: "The view is amazing." },
"Amount": { m: "পরিমাণ", e: "A large amount of money was spent." },
"Ancient": { m: "প্রাচীন", e: "This is an ancient temple." },
"Angry": { m: "রাগান্বিত", e: "Why are you angry?" },
"Animal": { m: "প্রাণী / পশু", e: "The lion is a wild animal." },
"Announce": { m: "ঘোষণা করা", e: "The teacher announced the exam date." },
"Answer": { m: "উত্তর", e: "Give me the correct answer." },
"Anywhere": { m: "যে কোনো স্থানে", e: "You can sit anywhere." },
"Apartment": { m: "অ্যাপার্টমেন্ট / ফ্ল্যাট", e: "They live in a new apartment." },
"Appear": { m: "উপস্থিত হওয়া / মনে হওয়া", e: "He appeared suddenly." },
"Apple": { m: "আপেল", e: "An apple a day keeps the doctor away." },
"Application": { m: "আবেদন / প্রয়োগ", e: "Submit your application form." },
"Apply": { m: "আবেদন করা / প্রয়োগ করা", e: "She applied for the job." },
"Approach": { m: "কাছাকাছি আসা / পদ্ধতি", e: "We are approaching the station." },
"Argue": { m: "যুক্তিতর্ক করা", e: "Don't argue with your parents." },
"Arrival": { m: "আগমন", e: "We waited for his arrival." },
"Arrive": { m: "পৌঁছানো", e: "When will the train arrive?" },
"Article": { m: "প্রবন্ধ / অনুচ্ছেদ", e: "I read an interesting article." },
"Artist": { m: "শিল্পী", e: "He is a famous artist." },
"Ashamed": { m: "লজ্জিত", e: "I am ashamed of my mistake." },
"Asleep": { m: "ঘুমন্ত", e: "The baby is fast asleep." },
"Assistant": { m: "সহকারী", e: "She works as a shop assistant." },
"Attack": { m: "আক্রমণ করা", e: "The dog attacked the stranger." },
"Attempt": { m: "চেষ্টা করা", e: "He made an attempt to escape." },
"Attend": { m: "উপস্থিত থাকা", e: "I will attend the meeting." },
"Attention": { m: "মনোযোগ", e: "Pay attention to the lesson." },
"Attract": { m: "আকর্ষণ করা", e: "Magnets attract iron." },
"Author": { m: "লেখক", e: "Who is the author of this book?" },
"Autumn": { m: "শরৎকাল", e: "Leaves fall in autumn." },
"Available": { m: "সহজলভ্য", e: "This book is available in the library." },
"Average": { m: "গড়", e: "His playing average is very good." },
"Avoid": { m: "এড়িয়ে চলা", e: "We should avoid junk food." },
"Awake": { m: "জাগ্রত", e: "Are you awake?" },
"Aware": { m: "সচেতন", e: "We should be aware of environment." },
"Awesome": { m: "দুর্দান্ত", e: "The movie was awesome." },
"Awful": { m: "ভয়ানক", e: "The weather is awful today." },
"Background": { m: "পটভূমি", e: "The picture has a blue background." },
"Baggage": { m: "মালপত্র", e: "Leave your baggage here." },
"Balance": { m: "ভারসাম্য", e: "Try to keep your balance." },
"Banana": { m: "কলা", e: "I like to eat banana." },
"Bank": { m: "ব্যাংক / তীর", e: "He works in a bank." },
"Base": { m: "ভিত্তি", e: "The glass has a heavy base." },
"Basic": { m: "মৌলিক", e: "Food is our basic need." },
"Basket": { m: "ঝুড়ি", e: "There are some fruits in the basket." },
"Battle": { m: "যুদ্ধ", e: "Many soldiers died in the battle." },
"Beach": { m: "সমুদ্রসৈকত", e: "We walked along the beach." },
"Beautiful": { m: "সুন্দর", e: "She is a beautiful girl." },
"Beauty": { m: "সৌন্দর্য", e: "The beauty of nature is amazing." },
"Because": { m: "কারণ", e: "I am late because of traffic." },
"Become": { m: "হওয়া", e: "He wants to become a doctor." },
"Bedroom": { m: "শয়নকক্ষ", e: "My bedroom is very small." },
"Before": { m: "আগে", e: "Look before you leap." },
"Begin": { m: "শুরু করা", e: "Let's begin the class." },
"Behave": { m: "আচরণ করা", e: "Behave yourself properly." },
"Behavior": { m: "আচরণ", e: "His behavior is very polite." },
"Behind": { m: "পিছনে", e: "The cat is behind the door." },
"Believe": { m: "বিশ্বাস করা", e: "I believe in Allah." },
"Belong": { m: "অধীন হওয়া", e: "This book belongs to me." },
"Below": { m: "নিচে", e: "Please read the text below." },
"Beside": { m: "পাশে", e: "Come and sit beside me." },
"Better": { m: "অধিকতর ভালো", e: "I feel much better today." },
"Between": { m: "দুইয়ের মাঝে", e: "The river flows between two fields." },
"Bicycle": { m: "সাইকেল", e: "He rides a bicycle to school." },
"Bitter": { m: "তিক্ত", e: "The medicine tastes bitter." },
"Blanket": { m: "কম্বল", e: "It is cold, take a blanket." },
"Blind": { m: "অন্ধ", e: "The man is blind in one eye." },
"Blood": { m: "রক্ত", e: "Blood is red." },
"Borrow": { m: "ধার করা", e: "Can I borrow your pen?" },
"Bottle": { m: "বোতল", e: "Give me a bottle of water." },
"Bottom": { m: "তলদেশ", e: "The ship sank to the bottom." },
"Branch": { m: "শাখা", e: "A bird is sitting on a branch." },
"Brave": { m: "সাহসী", e: "He is a brave soldier." },
"Bread": { m: "রুটি", e: "I eat bread and butter." },
"Break": { m: "ভাঙা", e: "Don't break the glass." },
"Breakfast": { m: "সকালের নাস্তা", e: "I have my breakfast at 8 am." },
"Breathe": { m: "নিঃশ্বাস নেওয়া", e: "We breathe to live." },
"Bridge": { m: "সেতু", e: "There is a bridge over the river." },
"Brief": { m: "সংক্ষিপ্ত", e: "Give a brief description." },
"Bright": { m: "উজ্জ্বল", e: "The sun is very bright." },
"Bring": { m: "আনা", e: "Bring me a glass of water." },
"Broad": { m: "প্রশস্ত", e: "The road is very broad." },
"Broken": { m: "ভাঙ্গা", e: "The chair is broken." },
"Brother": { m: "ভাই", e: "He is my elder brother." },
"Brown": { m: "বাদামী", e: "I have a brown bag." },
"Brush": { m: "ব্রাশ", e: "Brush your teeth daily." },
"Build": { m: "নির্মাণ করা", e: "Birds build nests in trees." },
"Business": { m: "ব্যবসা", e: "My father is in business." },
"Butter": { m: "মাখন", e: "I like bread with butter." },
"Button": { m: "বোতাম", e: "One button of my shirt is missing." },
"Cabinet": { m: "মন্ত্রিসভা / আলমারি", e: "Keep the files in the cabinet." },
"Calculate": { m: "হিসাব করা", e: "Calculate the total cost." },
"Calendar": { m: "ক্যালেন্ডার", e: "Check the date on the calendar." },
"Camera": { m: "ক্যামেরা", e: "He took photos with his camera." },
"Camp": { m: "শিবির", e: "We set up a camp in the forest." },
"Cancel": { m: "বাতিল করা", e: "The meeting was cancelled." },
"Cancer": { m: "ক্যান্সার", e: "Smoking can cause cancer." },
"Candidate": { m: "প্রার্থী", e: "He is an honest candidate." },
"Candle": { m: "মোমবাতি", e: "Light a candle, please." },
"Capital": { m: "রাজধানী / মূলধন", e: "Dhaka is the capital of Bangladesh." },
"Captain": { m: "অধিনায়ক", e: "He is the captain of our team." },
"Careful": { m: "সতর্ক", e: "Be careful when crossing the road." },
"Carpet": { m: "গালিচা", e: "There is a red carpet on the floor." },
"Carry": { m: "বহন করা", e: "Can you carry this bag?" },
"Catch": { m: "ধরা", e: "Try to catch the ball." },
"Cause": { m: "কারণ", e: "What was the cause of the fire?" },
"Celebrate": { m: "উদযাপন করা", e: "We will celebrate his birthday." },
"Center": { m: "কেন্দ্র", e: "The park is in the center of the town." },
"Central": { m: "কেন্দ্রীয়", e: "He works at the central bank." },
"Century": { m: "শতাব্দী", e: "A century has 100 years." },
"Ceremony": { m: "অনুষ্ঠান", e: "I attended the wedding ceremony." },
"Certain": { m: "নিশ্চিত", e: "I am certain he will come." },
"Chance": { m: "সুযোগ", e: "Give me one more chance." },
"Change": { m: "পরিবর্তন", e: "The weather changes often." },
"Chapter": { m: "অধ্যায়", e: "Read chapter five of this book." },
"Character": { m: "চরিত্র", e: "He is a man of good character." },
"Charge": { m: "অভিযোগ / মূল্য", e: "What is the charge for this service?" },
"Cheap": { m: "সস্তা", e: "This pen is very cheap." },
"Cheat": { m: "প্রতারণা করা", e: "It is a sin to cheat." },
"Check": { m: "পরীক্ষা করা", e: "Please check my homework." },
"Cheer": { m: "আনন্দিত করা", e: "The crowd cheered for the team." },
"Cheese": { m: "পনির", e: "Mice love cheese." },
"Chemical": { m: "রাসায়নিক", e: "Chemicals can be dangerous." },
"Chicken": { m: "মুরগির বাচ্চা / মাংস", e: "I'll have fried chicken for dinner." },
"Chief": { m: "প্রধান", e: "He is the chief guest of the event." },
"Child": { m: "শিশু", e: "A child is playing in the field." },
"Choose": { m: "বেছে নেওয়া", e: "You can choose any color." },
"Church": { m: "উপাসনালয় (খ্রিস্টান)", e: "They go to church on Sundays." },
"Circle": { m: "বৃত্ত", e: "Draw a circle on the paper." },
"Citizen": { m: "নাগরিক", e: "We are citizens of Bangladesh." },
"City": { m: "শহর", e: "Dhaka is a big city." },
"Class": { m: "শ্রেণি", e: "I read in class six." },
"Clean": { m: "পরিষ্কার", e: "Keep your room clean." },
"Clear": { m: "পরিষ্কার (স্পষ্ট)", e: "The sky is clear today." },
"Clerk": { m: "কেরানি", e: "He works as a clerk in an office." },
"Clever": { m: "চালাক", e: "The fox is a clever animal." },
"Climate": { m: "জলবায়ু", e: "The climate of this country is hot." },
"Climb": { m: "আরোহণ করা", e: "The boy is climbing the tree." },
"Clock": { m: "দেয়াল ঘড়ি", e: "Look at the clock." },
"Close": { m: "বন্ধ করা / কাছাকাছি", e: "Close the door." },
"Clothes": { m: "জামাকাপড়", e: "She bought new clothes." },
"Cloud": { m: "মেঘ", e: "The sky is full of dark clouds." },
"Coast": { m: "উপকূল", e: "We live near the coast." },
"Coffee": { m: "কফি", e: "I drink coffee in the morning." },
"Collect": { m: "সংগ্রহ করা", e: "I collect old coins." },
"Collection": { m: "সংগ্রহ", e: "He has a great stamp collection." },
"College": { m: "কলেজ", e: "My brother goes to college." },
"Color": { m: "রঙ", e: "What is your favorite color?" },
"Combine": { m: "একত্রিত করা", e: "Combine these two elements together." },
"Comfort": { m: "আরাম", e: "This chair gives me much comfort." },
"Command": { m: "আদেশ", e: "The officer commanded his soldiers." },
"Comment": { m: "মন্তব্য", e: "No comment on this matter." },
"Common": { m: "সাধারণ", e: "Fever is a common disease." },
"Community": { m: "সম্প্রদায়", e: "We should help our community." },
"Company": { m: "প্রতিষ্ঠান (কোম্পানি)", e: "He works in a software company." },
"Compare": { m: "তুলনা করা", e: "Do not compare yourself to others." },
"Complete": { m: "সম্পন্ন করা", e: "Complete your task quickly." },
"Condition": { m: "শর্ত / অবস্থা", e: "The patient is in serious condition." },
"Connect": { m: "সংযুক্ত করা", e: "Connect the two wires." },
"Consider": { m: "বিবেচনা করা", e: "Please consider my application." },
"Contain": { m: "ধারণ করা", e: "This box contains books." },
"Continue": { m: "চালিয়ে যাওয়া", e: "Continue reading." },
"Control": { m: "নিয়ন্ত্রণ", e: "Try to control your anger." },
"Cook": { m: "রান্না করা", e: "My mother cooks well." },
"Copy": { m: "অনুলিপি করা", e: "Don't copy others' homework." },
"Corner": { m: "কোণা", e: "Stand in the corner of the room." },
"Correct": { m: "সঠিক", e: "Your answer is correct." },
"Cost": { m: "খরচ / দাম", e: "What is the cost of this pen?" },
"Cotton": { m: "তুলা", e: "This shirt is made of pure cotton." },
"Count": { m: "গণনা করা", e: "Count the apples." },
"Country": { m: "দেশ", e: "Bangladesh is my country." },
"Course": { m: "কোর্স / গতিপথ", e: "I am taking an English course." },
"Cover": { m: "আচ্ছাদন করা / ঢাকা", e: "Cover the food." },
"Crash": { m: "ধাক্কা লাগা (দুর্ঘটনা)", e: "The car crashed into a tree." },
"Crazy": { m: "পাগল", e: "Are you crazy?" },
"Create": { m: "সৃষ্টি করা", e: "God created the earth." },
"Credit": { m: "ধার / স্বীকৃতি", e: "You can buy this by credit card." },
"Crime": { m: "অপরাধ", e: "Stealing is a crime." },
"Criminal": { m: "অপরাধী", e: "The police caught the criminal." },
"Cross": { m: "পার হওয়া", e: "Look carefully before you cross the road." },
"Crowd": { m: "জনতা / ভিড়", e: "There is a huge crowd in the market." },
"Crown": { m: "মুকুট", e: "The king wears a crown." },
"Cruel": { m: "নিষ্ঠুর", e: "Don't be cruel to animals." },
"Crush": { m: "পিষে ফেলা", e: "The machine will crush the stones." },
"Cry": { m: "কাঁদা", e: "Why is the baby crying?" },
"Culture": { m: "সংস্কৃতি", e: "We are proud of our culture." },
"Curious": { m: "কৌতূহলী", e: "The child is very curious." },
"Current": { m: "বর্তমান", e: "What is the current situation?" },
"Curtain": { m: "পর্দা", e: "Draw the curtain." },
"Curve": { m: "বক্ররেখা", e: "The road has a sharp curve." },
"Custom": { m: "প্রথা", e: "It is our local custom." },
"Customer": { m: "ক্রেতা", e: "The shop has many customers." },
"Damage": { m: "ক্ষতি করা", e: "The storm damaged the house." },
"Dance": { m: "নাচ করা", e: "She likes to dance." },
"Danger": { m: "বিপদ", e: "The tiger is a sign of danger." },
"Dangerous": { m: "বিপজ্জনক", e: "Playing with fire is dangerous." },
"Dark": { m: "অন্ধকার", e: "It gets dark after sunset." },
"Date": { m: "তারিখ", e: "What is the date today?" },
"Daughter": { m: "কন্যা", e: "She is my youngest daughter." },
"Dawn": { m: "ভোর", e: "We woke up at dawn." },
"Dead": { m: "মৃত", e: "The plant is dead." },
"Deal": { m: "চুক্তি / আচরণ করা", e: "It's a good deal." },
"Dear": { m: "প্রিয়", e: "My dear friend." },
"Death": { m: "মৃত্যু", e: "Death is inevitable." },
"Debate": { m: "বিতর্ক", e: "There was a long debate." },
"Debt": { m: "ঋণ", e: "He paid off his debt." },
"Decade": { m: "দশক", e: "A decade means ten years." },
"Decide": { m: "সিদ্ধান্ত নেওয়া", e: "He decided to go." },
"Decision": { m: "সিদ্ধান্ত", e: "It was a good decision." },
"Deep": { m: "গভীর", e: "The river is very deep." },
"Defeat": { m: "পরাজিত করা", e: "They defeated the enemy." },
"Defend": { m: "রক্ষা করা", e: "We must defend our country." },
"Degree": { m: "মাত্রা / ডিগ্রি", e: "Water boils at 100 degrees." },
"Delay": { m: "দেরি করা", e: "Do not delay." },
"Deliver": { m: "পৌঁছে দেওয়া", e: "The postman delivers letters." },
"Demand": { m: "চাহিদা", e: "There is a high demand for rice." },
"Dentist": { m: "দাঁতের চিকিৎসক", e: "I need to see a dentist." },
"Deny": { m: "অস্বীকার করা", e: "He denied the charge." },
"Depend": { m: "নির্ভর করা", e: "We depend on agriculture." },
"Describe": { m: "বর্ণনা করা", e: "Can you describe the man?" },
"Desert": { m: "মরুভূমি", e: "Sahara is a big desert." },
"Design": { m: "নকশা", e: "I like the design of this shirt." },
"Desire": { m: "বাসনা", e: "I have no desire for wealth." },
"Desk": { m: "ডেস্ক / বসার টেবিল", e: "Put the book on the desk." },
"Destroy": { m: "ধ্বংস করা", e: "The earthquake destroyed the city." },
"Detail": { m: "বিস্তারিত", e: "Tell me in detail." },
"Device": { m: "যন্ত্র", e: "This is a useful device." },
"Diamond": { m: "হীরা", e: "She wears a diamond ring." },
"Diary": { m: "ডায়েরি", e: "I keep a personal diary." },
"Dictionary": { m: "অভিধান", e: "Look up the word in a dictionary." },
"Differ": { m: "ভিন্ন হওয়া", e: "Our opinions may differ." },
"Difference": { m: "পার্থক্য", e: "What is the difference between these two?" },
"Different": { m: "আলাদা", e: "We are from different schools." },
"Difficult": { m: "কঠিন", e: "The math problem is difficult." },
"Dinner": { m: "রাতের খাবার", e: "I eat dinner at 9 PM." },
"Direct": { m: "সরাসরি", e: "Walk in a direct line." },
"Direction": { m: "দিক", e: "Which direction did he go?" },
"Dirty": { m: "নোংরা", e: "Don't wear dirty clothes." },
"Discover": { m: "আবিষ্কার করা", e: "Who discovered America?" },
"Discuss": { m: "আলোচনা করা", e: "Let's discuss the matter." },
"Disease": { m: "রোগ", e: "Cholera is a dangerous disease." },
"Dish": { m: "থালা / খাবার", e: "Wash the dish. / It is a tasty dish." },
"Distance": { m: "দূরত্ব", e: "The school is at a short distance." },
"Divide": { m: "ভাগ করা", e: "Divide the cake into two pieces." },
"Doctor": { m: "ডাক্তার", e: "The doctor is checking the patient." },
"Door": { m: "দরজা", e: "Open the door." },
"Double": { m: "দ্বিগুণ", e: "His salary was doubled." },
"Doubt": { m: "সন্দেহ", e: "I have no doubt about it." },
"Down": { m: "নিচে", e: "Please sit down." },
"Draw": { m: "আঁকা", e: "Draw a picture of a house." },
"Dream": { m: "স্বপ্ন", e: "I had a sweet dream last night." },
"Dress": { m: "পোশাক", e: "She is wearing a beautiful dress." },
"Drink": { m: "পান করা", e: "Drink plenty of water." },
"Drive": { m: "গাড়ি চালানো", e: "He drives carefully." },
"Drop": { m: "পড়তে দেয়া / ফোঁটা", e: "A drop of water. / Don't drop the glass." },
"Dust": { m: "ধুলা", e: "Wash the dust off your hands." },
"Duty": { m: "দায়িত্ব / কর্তব্য", e: "It is our duty to obey our parents." },
"Early": { m: "তাড়াতাড়ি", e: "I wake up early in the morning." },
"Earn": { m: "উপার্জন করা", e: "He earns a good salary." },
"Earth": { m: "পৃথিবী", e: "The earth rotates around the sun." },
"East": { m: "পূর্ব", e: "The sun rises in the east." },
"Easy": { m: "সহজ", e: "The test was very easy." },
"Edge": { m: "প্রান্ত / ধার", e: "Don't sit on the edge of the roof." },
"Educate": { m: "শিক্ষিত করা", e: "We should educate all children." },
"Education": { m: "শিক্ষা", e: "Education is the backbone of a nation." },
"Effect": { m: "প্রভাব / ফল", e: "The medicine had no effect." },
"Effort": { m: "প্রচেষ্টা", e: "He succeeded by his own effort." },
"Eight": { m: "আট", e: "I have eight friends." },
"Either": { m: "যেকোন একটি", e: "You can choose either of them." },
"Elect": { m: "নির্বাচিত করা", e: "They elected him as chairman." },
"Electric": { m: "বিদ্যুতিক", e: "This is an electric fan." },
"Element": { m: "উপাদান", e: "Honesty is an element of good character." },
"Elephant": { m: "হাতি", e: "An elephant has a long trunk." },
"Eleven": { m: "এগারো", e: "There are eleven players in a cricket team." },
"Else": { m: "অন্য কিছু", e: "Do you need anything else?" },
"Emotion": { m: "আবেগ", e: "He couldn't control his emotion." },
"Empty": { m: "খালি", e: "The box is empty." },
"Energy": { m: "শক্তি", e: "Food gives us energy." },
"Engine": { m: "ইঞ্জিন", e: "The car's engine stopped working." },
"English": { m: "ইংরেজি", e: "English is an international language." },
"Enjoy": { m: "উপভোগ করা", e: "I enjoy reading books." },
"Enough": { m: "যথেষ্ট", e: "I have enough money." },
"Enter": { m: "প্রবেশ করা", e: "Don't enter the room without permission." },
"Entire": { m: "সম্পূর্ণ", e: "He ate the entire cake." },
"Envelope": { m: "খাম", e: "Put the letter in the envelope." },
"Environment": { m: "পরিবেশ", e: "We should keep our environment clean." },
"Equal": { m: "সমান", e: "All parts are equal." },
"Equip": { m: "সজ্জিত করা", e: "The room is equipped with AC." },
"Error": { m: "ভুল", e: "There is an error in your calculation." },
"Escape": { m: "পালানো", e: "The bird escaped from the cage." }
};

let content = fs.readFileSync('src/data/class6VocabData.ts', 'utf-8');

for (const [word, trans] of Object.entries(dict)) {
  const meaningRegex = new RegExp(`meaning: "Class 6 Meaning for ${word}"`, "g");
  const exampleRegex = new RegExp(`example: "Class 6 Example sentence for ${word}"`, "g");
  
  content = content.replace(meaningRegex, `meaning: "${trans.m}"`);
  content = content.replace(exampleRegex, `example: "${trans.e}"`);
}

// Fallback replace for the rest that didn't match the dictionary
content = content.replace(/meaning: "Class 6 Meaning for ([^"]+)"/g, 'meaning: "$1 এর বাংলা অর্থ"');
content = content.replace(/example: "Class 6 Example sentence for ([^"]+)"/g, 'example: "$1 এর উদাহরণ বাক্য"');

fs.writeFileSync('src/data/class6VocabData.ts', content);
console.log('Update complete!');
