const fs = require('fs');

const idiomsRaw = `
A bad workman quarrels with his tools|নাচতে না জানলে উঠান বাঁকা
A bed of roses|আরামদায়ক সুখকর অবস্থা (A life of ease)
A big draw|প্রধান আকর্ষণ (An attraction)
A bird’s eye view|একনজরে সমগ্র দেখা (A cursory glance / Rough idea)
A black sheep|কুলাঙ্গার (A wicked person)
A bolt from the blue|বিনা মেঘে বজ্রপাত (An unexpected disaster)
A bone of contention|বিবাদের বিষয় (A subject of dispute)
A bull in a china shop|যে ব্যক্তি সব জায়গাতেই বিশৃঙ্খলা সৃষ্টি করে (Clumsy person)
A burning question|গুরুত্বপূর্ণ বিষয় (An important issue)
A call to arms|যুদ্ধে অংশগ্রহণের আহ্বান
A castle in the air|আকাশ কুসুম কল্পনা (Daydream)
A child’s play|অত্যন্ত সহজ কাজ (A very easy task)
A cock and bull story|গাঁজাখুরি গল্প (An absurd story)
A cold blooded murder|ঠান্ডা মাথায় খুন (A deliberate murder)
A crying need|জরুরি বা গুরুত্বপূর্ণ বিষয় (An urgent need)
A dark horse|অপরিচিত কিন্তু প্রতিভাবান ব্যক্তি (An unknown winner)
A dead letter|অকার্যকর, যা আর প্রচলিত নেই (A law which is no longer in force)
A fair weather friend|সুসময়ের বন্ধু (A friend in good times only)
A far cry|অনেক দূরের বিষয়, অসম্ভব ব্যাপার (A long distance away / Impossible)
A feather in one's cap|অতিরিক্ত সাফল্য বা সম্মান (An additional achievement)
A fish out of water|অস্বস্তিকর অবস্থা (In an uncomfortable position)
A fool's paradise|বোকার স্বর্গ (A state of false hope)
A gala day|উৎসবের দিন (A day of festivity)
A hard nut to crack|কঠিন সমস্যা বা ব্যক্তি (A difficult problem/person)
A house of cards|তাসের ঘর, ভঙ্গুর (A fragile plan)
A lame excuse|বাজে অজুহাত (A bad or invalid excuse)
A laughing stock|হাস্যকর পাত্র (An object of ridicule)
A maiden speech|প্রথম বক্তৃতা (First speech)
A man of letters|পণ্ডিত ব্যক্তি (A learned man)
A man of parts|গুণী ব্যক্তি (A man of talent)
A man of straw|দুর্বল বা অপদার্থ ব্যক্তি (A weak or worthless person)
A man of word|কথার দাম আছে এমন ব্যক্তি (A trustworthy person)
A narrow escape|অল্পের জন্য রক্ষা (Hairbreadth escape)
A needle in a haystack|খুঁজে পাওয়া অসম্ভব এমন কিছু
A nipper in the bud|অঙ্কুরে বিনাশ (Destroy in the very beginning)
A passing fancy|সাময়িক উত্তেজনা
A piece of cake|অত্যন্ত সহজ কাজ (A very easy task)
A rainy day|দুর্দিন বা কষ্টের দিন (A time of difficulty)
A red letter day|স্মরণীয় দিন (A memorable day)
A round peg in a square hole|অনুপযুক্ত ব্যক্তি (A misfit person)
A shadow of one's former self|পূর্বের চেয়ে দুর্বল বা কঙ্কালসার
A sleeping partner|নিষ্ক্রিয় অংশীদার (Inactive partner)
A slip of the pen|লেখায় সামান্য ভুল (A small mistake in writing)
A slip of the tongue|কথায় সামান্য ভুল (A mistake in speaking)
A snake in the grass|লুকানো শত্রু (An unseen enemy/danger)
A sore point|কষ্টের কারণ (A subject that causes anger or pain)
A squaring the circle|অসম্ভব কাজ (Attempting an impossible task)
A step in the dark|অনিশ্চিত পদক্ষেপ (An uncertain action)
A stone’s throw|খুব কাছাকাছি (Very near)
A storm in a teacup|তুচ্ছ বিষয়ে প্রবল উত্তেজনা (Great excitement about a trivial matter)
A thorn in one's side|বিরক্তির কারণ (A continuous source of annoyance)
A turncoat|দলত্যাগী, বিশ্বাসঘাতক (One who changes side/party)
A white elephant|দাম বেশি কিন্তু কাজে আসে না এমন কিছু (Expensive but useless)
A wild goose chase|পণ্ডশ্রম (A foolish and hopeless search)
Abide by|মেনে চলা (To obey)
Above all|সর্বোপরি (Most importantly)
Above board|সংশয়হীন, নিষ্কলুষ (Open and honest / Beyond suspicion)
Achilles' heel|দুর্বল দিক (A weak point / Vulnerable spot)
Acid test|কঠিন পরীক্ষা (A crucial test/proof)
Add fuel to the fire|আগুনে ঘি ঢালা, পরিস্থিতি খারাপ করা (To worsen the matter)
All and sundry|সবাই মিলে (Everyone without exception)
All at once|হঠাৎ (Suddenly)
All ear|মনোযোগ দিয়ে শোনা (Listening eagerly)
All in all|সর্বেসর্বা (Supreme / All powerful)
All Greek to me|সম্পূর্ণ অবোধ্য (Completely incomprehensible)
All on a sudden|হঠাৎ করে (Suddenly)
All the same|একই কথা (No difference)
Alpha and omega|শুরু থেকে শেষ পর্যন্ত (From beginning to end / ABC)
Apple of discord|বিবাদের মূল বিষয় (Subject of dispute)
Apple of one's eye|চোখের مণি, অতি আদরের (Extremely favorite)
Apple-pie order|পরিপাটি বা সাজানো অবস্থা (In perfect order)
Arm in arm|হাত ধরাধরি করে (Closely linked)
As a matter of fact|প্রকৃতপক্ষে (In reality / Actually)
As clear as day|দিনের আলোর মত স্পষ্ট (Very clear)
As fit as a fiddle|সুস্থ সবল (In very good health)
At a discount|অবজ্ঞাত (Undervalued)
At a loss|হতবুদ্ধি, কিংকর্তব্যবিমূঢ় (Puzzled / Confused)
At all events|যাই ঘটুক না কেন (In any case)
At arm's length|নিরাপদ দূরত্বে, নিকটে (At a safe distance / Near)
At daggers drawn|ভীষণ শত্রুতা (On the point of fighting / Hostile)
At eleventh hour|শেষ মুহূর্তে (At the last possible moment)
At home|দক্ষ, পরিচিত (Skilled / Comfortable)
At large|স্বাধীন, মুক্ত (Free)
At least|অন্ততপক্ষে (At the minimum)
At one's beck and call|আজ্ঞাবহ (Ready to obey orders)
At one's wits' end|হতবুদ্ধি অবস্থা (Puzzled)
At random|বেপরোয়াভাবে, এলোমেলোভাবে (Aimlessly)
At sixes and sevens|এলোমেলো অবস্থা (In confusion or disorder)
At stake|বিপন্ন (In danger)
At the outset|শুরুতে (At the very beginning)
At the drop of a hat|তাত্ক্ষণিকভাবে (Instantly / Without hesitation)
At the bottom of|মূল কারণ (The root cause)
Avail oneself of|সুযোগ গ্রহণ করা (To take advantage of)
Awkward age|কৈশোরকাল (Adolescence)
Back and belly|সর্বস্ব (Everything)
Back out|পিছিয়ে যাওয়া (Withdraw from an agreement)
Back up|সমর্থন করা (To support)
Bad blood|শত্রুতা, মনোমালিন্য (Enmity / Ill feeling)
Bag and baggage|তল্পিতল্পাসহ (With all belongings)
Baker's dozen|তেরটি (Thirteen)
Bandy words|তর্কাতর্কি করা (Argue)
Bank on|নির্ভর করা (Depend on)
Barely makes ends meet|কষ্টে জীবনযাপন করা
Barking dogs seldom bite|যত গর্জে তত বর্ষে না (Threats are rarely executed)
Be all ears|মনোযোগ দিয়ে শোনা (Listen attentively)
Be in bad books|কারো সুনজরে না থাকা (Out of favor)
Be in good books|কারো সুনজরে থাকা (In favor with someone)
Be in the dark|অজ্ঞ থাকা (Knowing nothing)
Be out of order|নষ্ট হওয়া, বিকল হওয়া (Not working properly)
Bear in mind|মনে রাখা (Remember)
Bear the brunt of|প্রধান ঝক্কি পোহানো (To endure the main force or shock)
Beat about the bush|কাজের কথায় না এসে অপ্রাসঙ্গিক কথা বলা (To avoid the main point)
Beat back|পিছিয়ে আসতে বাধ্য করা (Force to retreat)
Beat black and blue|নির্মমভাবে প্রহার করা (Beat severely)
Beat the air|বৃথা চেষ্টা করা (Useless effort)
Bed of thorns|কণ্টকশয্যা / কষ্টদায়ক অবস্থা (A state of extreme difficulty)
Before long|শীঘ্রই (Soon)
Behind the scenes|গোপনে (In secret)
Bell the cat|নেতৃত্ব দেওয়া বা ঝুঁকি নেওয়া (To take the lead in danger)
Below the mark|মানহীন (Below proper standard)
Beside the point|অপ্রাসঙ্গিক (Irrelevant)
Better half|স্ত্রী বা জীবনসঙ্গী (Wife)
Between the devil and the deep sea|শ্যাম রাখি না কূল রাখি (Between two dangers)
Beyond all question|সন্দেহাতীতভাবে (Undoubtedly)
Beyond doubt|সন্দেহের অতীত (Without a doubt)
Beyond measure|সীমাহীন (Boundless)
Bid fair|আশা করা (To seem likely)
Big bug / Big gun / Big wig|গুরুত্বপূর্ণ ব্যক্তি (Important person)
Bird of passage|অস্থায়ী বাসিন্দা (A temporary resident / wanderer)
Birds of a feather|একই স্বভাবের লোক (People of the same sort)
Black and blue|নির্মমভাবে (Severely)
Black and white|লিখিতভাবে (In writing)
Black out|জ্ঞান হারানো (To lose consciousness)
Black sheep|কুলাঙ্গার (Wicked/Worthless person)
Blind alley|যে রাস্তার শেষ নেই বা অবরুদ্ধ অবস্থা (A situation offering no hope of progress)
Blind to|দোষের প্রতি অন্ধ/উদাসীন (Unaware of someone's faults)
Block head|নির্বোধ (A stupid person)
Blood is thicker than water|রক্তের টান বড় টান (Family ties are strongest)
Blow one's own trumpet|অহংকার করা বা নিজের ঢোল নিজে পেটানো (To boast)
Blue blood|আভিজাত্য (Aristocratic birth)
Blue chip|সবচেয়ে নিরাপদ ও লাভজনক বিনিয়োগ (A reliable investment)
Board of trade|বাণিজ্যিক সংস্থা
Body and soul|সর্বান্তকরণে (With all energy / Completely)
Bone of contention|বিবাদের বিষয় (Matter of dispute)
Book worm|বইয়ের পোকা (A great reader)
Born with a silver spoon in one's mouth|ধনী পরিবারে জন্মগ্রহণ করা (Born of wealthy parents)
Bosom friend|অন্তরঙ্গ বন্ধু (An intimate friend)
Bottom line|মূল কথা বা সারসংক্ষেপ (The essential point)
Bound for|কোনো দিকে যাত্রা শুরু করা (To proceed to)
Bread and butter|জীবিকা (Livelihood)
Break down|ভেঙে পড়া (To fail / To collapse)
Break the ice|নীরবতা ভাঙা (To start conversation / overcome reserve)
Breathe one's last|মারা যাওয়া (To die)
Bring to book|শাস্তি দেওয়া (To punish / call to account)
Bring to light|প্রকাশ করা (To make known / reveal)
Bring to pass|ঘটনো (Cause to happen)
Broad daylight|দিনের বেলায় (During the day)
Broken reed|অবিশ্বস্ত লোক (An untrustworthy person)
Brown study|দিবাস্বপ্ন (Daydream / Deep thought)
Brute force|বর্বর শক্তি (Physical force instead of reason)
Build a castle in the air|আকাশ কুসুম কল্পনা করা (Make imaginary schemes)
Bull market|শেয়ারের উর্ধ্বগতিসম্পন্ন বাজার (A financial market with rising prices)
Burn the midnight oil|অনেক রাত জেগে কাজ বা পড়াশোনা করা (To study or work late into the night)
Burning question|তীব্র আলোচনার বিষয় (An important topic of discussion)
Burry the hatchet|বিবাদ মীমাংসা করা (To make peace / forget enmity)
By all means|যেকোনো উপায়ে / নিশ্চিতভাবে (In every possible way / Certainly)
By and by|শীঘ্রই / ক্রমান্বয়ে (Gradually / Soon)
By and large|সাধারণভাবে (Mostly / Generally)
By chance|হঠাৎ করে (Accidentally)
By dint of|প্রভাবে বা সাহায্যে (By means of)
By far|সর্বাংশে বা বহুলাংশে (By a great deal / mostly)
By fits and starts|অনিয়মিতভাবে (Irregularly)
By hook or by crook|যেকোনো উপায় অবলম্বন করে (By any means fair or foul)
By leaps and bounds|অতি দ্রুতগতিতে (Very rapidly)
By no means|কোনো মতেই না (In no way / Not at all)
By turns|পর্যায়ক্রমে (One after another)
By virtue of|গুণে বা কারণে (By means of / because of)
Call a spade a spade|সরাসরি বা অবকপটে কথা বলা (Speak frankly and directly)
Call in question|সন্দেহ করা (To doubt)
Call it a day|কাজ শেষ করা বা বিরতি দেওয়া (To stop working on something)
Call to mind|স্মরণ করা (Remember)
Capital punishment|মৃত্যুদণ্ড (Death penalty)
Carry the day|জয়লাভ করা (Win)
Cast a slur upon|কলঙ্ক লেপন করা (To bring disgrace upon)
Castles in the air|আকাশকুসুম কল্পনা (Daydreams)
Cat and dog life|কলহপূর্ণ জীবন (Life full of quarrels)
Catch red-handed|হাতে-নাতে ধরা (To catch in the act of committing a crime)
Cats and dogs|মুষলধারে বৃষ্টি (Raining heavily)
Chapter and verse|পুঙ্খানুপুঙ্খরূপে (Fully and precisely)
Cheek by jowl|অন্তরঙ্গভাবে ঘনিষ্ট (Side by side / intimately)
Child's play|সহজ কাজ (An easy task)
Cock and bull story|গাঁজাখুরি গল্প (A ridiculous and implausible story)
Cold blood|ঠান্ডা মাথায় (Unfeeling / deliberate)
Come of age|সাবালক হওয়া (Reach maturity)
Come to light|প্রকাশিত হওয়া (Be revealed)
Come true|সত্যে পরিণত হওয়া (Be proved true)
Cope with|মোকাবিলা করা (To deal successfully with)
Crocodile tears|মায়াকান্না / কপট কান্না (False show of sympathy)
Cry for the moon|অসম্ভব কিছু চাওয়া (Ask for the impossible)
Cry in the wilderness|অরণ্যে রোদন / বৃথা আবেদন (A futile appeal)
Cry over spilt milk|অতীতের কোনো ভুলের জন্য অনুশোচনা করা (Complain about what cannot be fixed)
Cut a sorry figure|খারাপ ফলাফল করা (Make a poor impression)
Cut one's coat according to one's cloth|আয় বুঝে ব্যয় করা (Live within one's means)
Dagger's drawn|ভীষণ শত্রুতা (Bitter enmity)
Dark horse|অপরিচিত বা গুপ্ত প্রতিভাবান ব্যক্তি (A person whose abilities are hidden)
Day dream|দিবাস্বপ্ন (A reverie)
Dead against|তীব্র বিরোধী (Strongly opposed)
Dead language|অপ্রচলিত ভাষা (A language no longer spoken)
Dead letter|অকার্যকর আইন (A law no longer observed)
Dead of night|মাঝরাত (Middle of the night)
Defacto|প্রকৃতপক্ষে (In reality / in fact)
Dejure|আইনগতভাবে (By right / according to law)
Die in harness|কাজ করতে করতে মারা যাওয়া (Die while working)
Dog days|সবচেয়ে গরমের দিনগুলো (Hottest days of summer)
Draw the line|সীমা নির্ধারণ করা (To set a limit)
Drop out|ঝরে পড়া (Leave before finishing)
Due to|কারণে (Because of)
Eager beaver|খুবই উৎসাহী ব্যক্তি (A very enthusiastic person)
Eagle-eyed|তীক্ষ্ণ দৃষ্টিসম্পন্ন (Sharp-sighted)
Eat humble pie|অপমান হজম করা (Suffer humiliation / accept defeat)
Eat one's words|ক্ষমা চাওয়া / কথা ফিরিয়ে নেওয়া (To admit oneself wrong)
End in smoke|ব্যর্থতায় পর্যবসিত হওয়া (Come to nothing)
En route|পথিমধ্যে (On the way)
Every inch|পুরোপুরি (Completely)
Every now and then|মাঝে মাঝে (Occasionally)
Eye wash|ধোঁকা দেওয়া / প্রতারণা (Deception / False display)
Face to face|সরাসরি / সামনাসামনি (Directly)
Fag end|শেষ ভাগ (The last part)
Fair and square|সৎ ও সরল (Honest and fair)
Fair play|সৎ এবং ন্যায়সংগত আচরণ (Just and honest dealing)
Fair weather friend|সুসময়ের বন্ধু (A friend in prosperous times only)
Fall a victim to|শিকার হওয়া (To suffer from)
Fall back on|নির্ভর করা (To rely on for support)
Fall flat|কোনো ফল না দেওয়া / নিষ্ফল হওয়া (Fail to produce any effect)
Fall out|ঝগড়া করা (Quarrel)
Fall short of|অপ্রতুল হওয়া / ঘাটতি হওয়া (To prove inadequate)
False steps|ভুল পদক্ষেপ বা সিদ্ধান্ত (A mistaken action)
Familiar with|সুপরিচিত (Well acquainted)
Far and near|সবদিক থেকে (From all directions)
Far and wide|সর্বত্র (Everywhere)
Fell in love with|প্রেমে পড়া (Begin to love)
Few and far between|কদাচিৎ (Very rare)
Fight shy of|এড়িয়ে চলা (To avoid)
Fight tooth and nail|প্রাণপণে যুদ্ধ করা (To fight with all energy)
Fish in troubled waters|অন্যের বিপদের সুযোগ নেওয়া (To gain advantage from someone's trouble)
Fish out of water|অস্বস্তিকর অবস্থা (Uncomfortable situation)
Flesh and blood|রক্ত-মাংসের শরীর (Human nature)
Fly in the face of|অবজ্ঞা করা (To disregard openly)
Fool's paradise|বোকার স্বর্গ (Unrealistic hope)
For good|চিরতরে (Forever)
For the sake of|কারণে বা জন্য (On account of / for the benefit of)
French leave|বিনা অনুমতিতে প্রস্থান (Departure without permission)
Fresh blood|নতুন বা তরুণ সদস্য (New members/blood)
From A to Z|শুরু থেকে শেষ পর্যন্ত (Everything completely)
From door to door|দ্বারে দ্বারে (From one house to another)
From hand to mouth|দিন এনে দিন খাওয়া (Living with just enough money)
Fund of knowledge|প্রচুর জ্ঞান (A large amount of knowledge)
Gala day|উৎসবের দিন (Day of festivity)
Get by heart|মুখস্থ করা (Learn strictly by memory)
Get rid of|মুক্তি পাওয়া (Be free from)
Get the upper hand|কাজে জয়লাভ করা / সুবিধা পাওয়া (To gain advantage)
Gift of the gab|বাচনভঙ্গি বা কথা বলার ক্ষমতা (Fluency of speech)
Give in|বশ্যতা স্বীকার করা (To surrender)
Give one the cold shoulder|উপেক্ষা করা (Treat with indifference)
Give piece of mind|ভর্ৎসনা করা (To scold)
Give up the ghost|মারা যাওয়া (To die)
Go astray|বিপথে চলা (Go on the wrong path)
Go to the dogs|গোল্লায় যাওয়া / ধ্বংস হওয়া (To be ruined)
Golden mean|মধ্যপন্থা (A middle course between extremes)
Good for nothing|অপদার্থ (Useless)
Green horn|অনভিজ্ঞ (An inexperienced person)
Green room|সাজঘর (Actors' resting room in a theatre)
Half-hearted|অনিচ্ছাকৃত (Without enthusiasm)
Hale and hearty|সুস্থ-সবল (Healthy and vigorous)
Hand in glove|অন্তরঙ্গ (Intimate / Very close)
Hand in hand|একযোগে (Together)
Hand to mouth|দিন এনে দিন খাওয়া (Scarcely making a living)
Hard and fast|বাঁধাধরা (Strict / fixed)
Hard nut to crack|কঠিন সমস্যা (A difficult problem)
Hard times|দুঃসময় (Difficult times)
Have a go|চেষ্টা করা (Make an attempt)
Head in the clouds|দিবাস্বপ্ন দেখা (Daydreaming / Impractical)
Heart and soul|সর্বান্তকরণে (With all energy / Earnestly)
Heavy rain|মুষলধারে বৃষ্টি (Pouring rain)
High and dry|অসহায় অবস্থায় (Helpless / Stranded)
High and low|সকল স্তরের মানুষ (People from all classes)
High time|যথোপযুক্ত সময় (The most appropriate time)
Hold good|খাটা বা প্রযোজ্য হওয়া (Remain valid)
Hold water|ধোপে টেকা বা বিশ্বাসযোগ্য হওয়া (To bear examination / Stand scrutiny)
Hole and corner|গোপন (Secret / furtive)
Hot potato|সমস্যা বা বিতর্কমূলক বিষয় (A controversial issue)
Hue and cry|শোরগোল (A loud public outcry)
Hush money|ঘুষ (Bribe money to keep silent)
In a body|একযোগে বা একত্রে (Together / As a whole)
In a fix|মহাসমস্যায় (In a difficult situation / Dilemma)
In a hurry|তাড়াহুড়োর মধ্যে (In haste)
In a nutshell|সংক্ষেপে (Briefly)
In accordance with|অনুসারে (According to)
In addition to|অধিকন্তু (Besides)
In any case|যাই হোক না কেন (Under any circumstances)
In black and white|লিখিতভাবে (In writing)
In cold blood|ঠান্ডা মাথায় বা ভেবে-চিন্তে (Deliberately)
In full swing|পুরোদমে (At the height of activity)
In good time|সময়মতো (Punctually)
In lieu of|পরিবর্তে (Instead of)
In order to|উর্দেশ্যে বা কারণে (For the purpose of)
In point of|বিষয়ে বা ক্ষেত্রে (In regard to)
In quest of|অন্বেষণে বা খোঁজে (In search of)
In respect of|বিষয়ে বা স্বপক্ষে (With regard to)
In spite of|সত্ত্বেও (Despite)
In the dark|অজ্ঞ বা অন্ধকারে (Ignorant of)
In the face of|বিপরীতে বা সামনে (In opposition to / confronted with)
In the final analysis|শেষমেশ বা সর্বোপরি (Ultimately)
In the good books of|সুনজরে বা বিশ্বাসভাজন (In favor with)
In the long run|অবশেষে বা পরিণামে (Eventually / ultimately)
In the nick of time|ঠিক সময়ে বা শেষ মুহূর্তে (Just at the right moment)
In the teeth of|তীব্র বিরোধিতার মুখে (In direct opposition to)
In the wake of|অব্যবহিত পরে বা ফলে (Following immediately after)
In vain|বৃথা বা নিষ্ফল (Without success / To no purpose)
Ins and outs|খুঁটিনাটি বা বিস্তারিত (The full details)
Iron out|মীমাংসা করা বা সমাধান করা (To resolve)
Iron will|দৃঢ় সংকল্প (Unbending resolution)
Jack of all trades|যে ব্যক্তি সব কাজেই মোটামুটি দক্ষ কিন্তু কোনোটাতেই বিশেষজ্ঞ নয় (A person who can do many different types of work)
Keep an eye on|নজর রাখা (To watch over)
Keep body and soul together|কোনোরকমে বেঁচে থাকা (To maintain life / barely survive)
Keep in mind|মনে রাখা বা স্মরণে থাকা (To remember)
Keep one's head|স্থির বা শান্ত থাকা (To remain calm)
Keep pace with|তাল মিলিয়ে চলা (To move at the same rate as)
Keep up with|সমান তালে চলা (To maintain the same speed)
Kick the bucket|মারা যাওয়া (To die)
Kith and kin|আত্মীয়স্বজন বা জ্ঞাতিগোষ্ঠী (Relatives / family members)
Know no bounds|সীমা না থাকা (To be limitless or boundless)
Lame excuse|বাজে অজুহাত (A weak or unconvincing excuse)
Lay down|উৎসর্গ করা বা ত্যাগ করা (To sacrifice / surrender)
Leave no stone unturned|কোনো চেষ্টা বাকি না রাখা (To try every possible means)
Leave out in the cold|উপেক্ষা করা বা বাদ দেওয়া (To ignore / neglect)
Lion's share|সিংহভাগ বা বৃহৎ অংশ (The largest portion)
Look down upon|ঘৃণার চোখে দেখা বা অবজ্ঞা করা (To despise / contemn)
Look for|খোঁজা (To search for)
Look forward to|আশায় পথ চেয়ে থাকা বা প্রত্যাশা করা (To expect with pleasure)
Look into|তদন্ত করা (To investigate)
Lose heart|হতাশ হওয়া বা ভগ্নোৎসাহ হওয়া (To become discouraged)
Make a clean breast of|বিনা সংকোচে স্বীকার করা বা স্বীকারোক্তি দেওয়া (To confess fully)
Make a mess of|তালগোল পাকানো বা ভণ্ডুল করা (To botch or bungle)
Make amends for|ক্ষতিপূরণ দেওয়া (To compensate for)
Make both ends meet|আয় বুঝে ব্যয় করা বা কোনো রকমে দিনাতিপাত করা (To earn just enough to live)
Make fun of|উপহাস করা বা ঠাট্টা করা (To ridicule)
Make good|ক্ষতিপূরণ করা বা সফল হওয়া (To compensate / to succeed)
Make out|বুঝতে পারা (To understand)
Make room for|জায়গা করে দেওয়া (To provide space for)
Make sure|নিশ্চিত করা (To ensure / verify)
Make up one's mind|মনস্থির করা বা সংকল্প করা (To decide)
Man of letters|পণ্ডিত ব্যক্তি বা সাহিত্যিক (A learned person)
Man of parts|গুণী বা বহুমুখী প্রতিভার অধিকারী ব্যক্তি (A person of diverse skills)
Man of straw|অপদার্থ বা অপদার্থ ব্যক্তি (A worthless person / weak character)
Maiden speech|প্রথম বক্তৃতা (First speech)
Mark my words|আমার কথা লিখে রাখো বা মনে রেখো (Pay attention to what I say)
Meet with|সম্মুখীন হওয়া বা সাক্ষাৎ ঘটা (To encounter / experience)
Mother wit|স্বাভাবিক বুদ্ধি বা কাণ্ডজ্ঞান (Common sense / native intelligence)
Move heaven and earth|আকাশ-পাতাল এক করা বা সম্ভাব্য সব চেষ্টা করা (To make every possible effort)
Narrow escape|অল্পের জন্য রক্ষা পাওয়া (A close shave / barely escaping danger)
Nip in the bud|অঙ্কুরে বিনাশ করা বা শুরুতেই নষ্ট করা (To stop something at the very beginning)
No doubt|নিঃসন্দেহে (Without a doubt / certainly)
Null and void|বাতিল বা অকার্যকর (Invalid / of no legal effect)
Of course|অবশ্যই (Certainly)
Of late|ইদানীং বা সম্প্রতি (Recently)
Of no avail|নিষ্ফল বা কোনো কাজে না আসা (Useless / ineffectual)
Off and on|মাঝে মাঝে বা সময়ে সময়ে (Occasionally / intermittently)
On account of|কারণে বা জন্যে (Because of)
On behalf of|পক্ষে বা তরফ থেকে (As a representative of)
On no account|কোনো মতেই না (Under no circumstances)
On the brink of|প্রান্তসীমায় বা দ্বারপ্রান্তে (On the verge of)
On the contrary|পক্ষান্তরে বা বিপরীতপক্ষে (In opposition to / on the other hand)
On the eve of|প্রাক্কালে বা পূর্ব মুহূর্তে (Just before)
On the spur of the moment|তাত্ক্ষণিকভাবে বা হঠাত্ করে (Impulsively / without planning)
On the verge of|প্রান্তসীমায় বা কাছাকাছি (On the brink of)
On the whole|মোটের উপর বা সাধারণভাবে (Generally speaking / considering everything)
Once and again|বারবার (Repeatedly)
Once for all|চিরতরে বা শেষবারের মতো (Finally and permanently)
Once in a blue moon|কদাচিৎ বা কালেভদ্রে (Very rarely)
Open secret|যে গোপন কথা সবাই জানে (A secret that is widely known)
Out and out|সম্পূর্ণরূপে বা হাড়ে হাড়ে (Completely / thoroughly)
Out of date|সেকেলে বা অপ্রচলিত (Old-fashioned / obsolete)
Out of doors|বাড়ির বাইরে (Outside)
Out of order|নষ্ট বা বিকল (Not working properly)
Out of place|বেমানান বা অপ্রাসঙ্গিক (Inappropriate)
Out of sorts|অসুস্থ বা মেজাজ খারাপ (Unwell / in a bad mood)
Out of the question|অসম্ভব বা অকল্পনীয় (Impossible)
Out of the wood|বিপদমুক্ত (Free from danger or difficulty)
Over and above|অধিকন্তু বা সর্বোপরি (In addition to / besides)
Part and parcel|অবিচ্ছেদ্য অংশ বা অপরিহার্য অংশ (An essential part)
Pay attention to|মনোযোগ দেওয়া (To focus on / heed)
Play a trick on|প্রতারণা করা বা ধোঁকা দেওয়া (To deceive or play a joke on)
Play foul|প্রতারণা করা বা চালাকি করা (To act dishonestly)
Play truant|স্কুল পালানো বা ফাঁকি দেওয়া (To stay away from school without permission)
Point blank|সরাসরি বা স্পষ্টত (Directly and plainly)
Pros and cons|খুঁটিনাটি বা ভালো-মন্দ দিক (The advantages and disadvantages / ins and outs)
Put up with|সহ্য করা বা মেনে নেওয়া (To tolerate or endure)
Rank and file|সাধারণ মানুষ বা সাধারণ সদস্য (The ordinary members / the common people)
Red-handed|হাতে-নাতে বা অপরাধ করা অবস্থায় (In the very act of committing a crime)
Red-letter day|স্মরণীয় দিন বা গুরুত্বপূর্ণ দিন (A memorable or important day)
Right and left|সবদিকে বা যথেচ্ছভাবে (In all directions)
Round the clock|দিনরাত বা অবিরাম (All day and all night)
Rule out|বাতিল করা বা বাদ দেওয়া (To reject or eliminate)
Run short of|ফুরিয়ে যাওয়া বা ঘাটতি পড়া (To not have enough of)
Safe and sound|নিরাপদ ও সুস্থ (Unharmed and free from danger)
Set fire to|আগুন ধরানো (To ignite)
Set in|শুরু হওয়া (প্রতিকূল কিছু) (To begin and seem likely to continue)
Set off|যাত্রা শুরু করা (To start a journey)
Set up|স্থাপন করা বা প্রতিষ্ঠা করা (To establish)
Show one's true colors|আসল রূপ প্রকাশ করা (To reveal one's real character)
Sine die|অনির্দিষ্টকালের জন্য (Indefinitely)
Slow coach|কুঁড়ে বা অলস ব্যক্তি (A slow or lazy person)
Small talk|সাধারণ বা মামুলি কথাবার্তা (Light conversation)
Smell a rat|সন্দেহ করা বা বিপদের গন্ধ পাওয়া (To suspect something is wrong)
Snake in the grass|লুকানো শত্রু (A hidden enemy)
So far as|যতদূর পর্যন্ত (To the extent that)
So to speak|এক কথায় বা বলতে গেলে (Used to explain something in a specific way)
Spare no pains|বিন্দুমাত্র ত্রুটি না করা বা সব ধরনের চেষ্টা করা (To make every possible effort)
Speak volumes for|সপ্রমাণ করা বা জোরালো প্রমাণ দেওয়া (To express a lot without words)
Square deal|সত্ বা ন্যায়সংগত লেনদেন (A fair and honest transaction)
Stand by|পাশে থাকা বা সমর্থন করা (To support or remain loyal to)
Stand in good stead|কাজে আসা বা উপকারে লাগা (To be useful or helpful to someone)
Status quo|বিদ্যমান অবস্থা বা পূর্বাবস্থা (The existing state of affairs)
Steer clear of|এড়িয়ে চলা (To avoid)
Step by step|ধাপে ধাপে বা ক্রমান্বয়ে (Gradually)
Stick to|লেগে থাকা বা অটল থাকা (To remain faithful to or continue doing)
Stone's throw|খুব কাছে (A very short distance)
Storm in a teacup|তুচ্ছ বিষয়ে প্রবল উত্তেজনা (A lot of unnecessary anger and worry about a matter that is not important)
Stumbling block|বাধা বা অন্তরায় (An obstacle or hindrance)
Sum and substance|সারসংক্ষেপ বা মূলকথা (The essential part or meaning)
Swan song|শেষ কীর্তি বা শেষ কাজ (The final performance or work before death or retirement)
Take aback|বিস্মিত হওয়া বা অবাক হওয়া (To surprise or shock someone)
Take advantage of|সুযোগ নেওয়া (To make use of an opportunity)
Take after|সদৃশ হওয়া বা দেখতে একই রকম হওয়া (To resemble a parent or ancestor)
Take for granted|ধরে নেওয়া বা সত্য বলে মেনে নেওয়া (To assume to be true without questioning)
Take into account|বিবেচনা করা (To consider)
Take place|ঘটা (To happen)
Take the bull by the horns|সাহসের সঙ্গে বিপদের মোকাবিলা করা (To face a difficult situation directly and courageously)
Take to heart|মর্মাহত হওয়া বা গুরুত্ব সহকারে নেওয়া (To be deeply affected by / take seriously)
Take to task|ভর্ৎসনা করা বা তিরস্কার করা (To scold or reprimand)
Tell upon|ক্ষতি করা (To have a bad effect on)
Through and through|সম্পূর্ণরূপে বা হাড়ে হাড়ে (Completely / thoroughly)
Throw cold water on|নিরুৎসাহিত করা (To discourage)
To and fro|এদিক ওদিক বা সামনে-পেছনে (Backwards and forwards)
To the backbone|হাড়ে হাড়ে বা পুরোপুরি (Thoroughly / completely)
To the contrary|বিপরীতপক্ষে বা উল্টোদিকে (On the other hand / opposite)
To the letter|অক্ষরে অক্ষরে বা হুবহু (Exactly / to the smallest detail)
To the point|যথাযথ বা প্রাসঙ্গিক (Relevant / exact)
Tooth and nail|প্রাণপণে বা সর্বশক্তি দিয়ে (With all one's resources or energy)
Turn a deaf ear to|উপেক্ষা করা বা কর্ণপাত না করা (To ignore or refuse to listen)
Turn down|প্রত্যাখ্যান করা (To reject)
Turn over a new leaf|নতুন জীবন বা নতুন অধ্যায় শুরু করা (To begin anew / change one's behavior for the better)
Turn the tide|মোড় ঘোরানো বা পরিস্থিতি পরিবর্তন করা (To reverse the course of events)
Under a cloud|সন্দেহের চোখে বা নিন্দিত (Under suspicion / in disgrace)
Under lock and key|তালাবদ্ধ বা নিরাপদ অবস্থায় (Securely locked away)
Up and doing|তত্পর বা কর্মোদ্যোগী (Active and busy)
Up to the mark|আশানুরূপ বা মানসম্মত (Of the required standard)
Ups and downs|উত্থান-পতন বা ভালো-মন্দ সময় (Fortunes and misfortunes / alternating periods of good and bad)
Wait upon|সেবা করা বা পরিচর্যা করা (To attend to or serve)
Wear and tear|ক্ষয়ক্ষতি (Damage resulting from ordinary use)
Well off|স্বচ্ছল বা ধনী (Wealthy / in good circumstances)
White elephant|ব্যয়বহুল অথচ অকেজো (Expensive to maintain but of no use)
Whole-hearted|আন্তরিক বা সর্বান্তকরণে (Sincere / completely committed)
Wild goose chase|পণ্ডশ্রম বা বৃথা খোঁজ (A foolish and hopeless pursuit)
With a view to|উদ্দেশ্যে (With the intention of)
With an eye to|উদ্দেশ্যে বা লক্ষ্য রেখে (With a view to / considering)
With flying colors|গর্বের সাথে বা সফলভাবে (Victoriously / with great success)
Without out|অবিরাম বা একটানা (Continuously / without stopping)
Word for word|অক্ষরে অক্ষরে বা হুবহু (Exactly as written or spoken)
Work out|সমাধান করা বা সম্পন্ন করা (To solve or figure out)
Worth one's while|লাভজনক বা সময় ও শ্রমের উপযুক্ত (Profitable / worth the time and effort)
Yellow press|হলুদ সাংবাদিকতা বা অতিরঞ্জিত সংবাদ (Sensational journalism)
`;

let idx = 100;
const wordItems = idiomsRaw.split('\n').filter(line => line.trim().length > 0).map((line) => {
    const [wordPart, banglaEngl] = line.split('|');
    if (!banglaEngl) {
        console.log(line);
        return null;
    }
    const [meaning, ...engParts] = banglaEngl.split(' (');
    let engStr = engParts.join('(');
    if (engStr.trim()) {
        engStr = engStr.trim().slice(0, -1); // remove trailing ')'
    }
    return {
        id: "idiom_bcs_bank_" + idx++,
        word: wordPart.trim(),
        language: "english",
        category: "idiom_phrase",
        meaning: meaning.trim() + (engStr ? " (" + engStr.trim() + ")" : ""),
        synonyms: [],
        antonyms: [],
        example: engStr ? engStr.trim() : ""
    };
}).filter(Boolean);

const fileContent = `import { WordItem } from "./vocabularyData";

export const IDIOMS_AND_PHRASES: WordItem[] = ${JSON.stringify(wordItems, null, 2)};
`;

fs.writeFileSync('src/data/idiomPhraseData.ts', fileContent);
console.log('Successfully wrote to src/data/idiomPhraseData.ts');
